name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Install
        run: |
          yarn install

      - name: Release for Windows
        if: matrix.os == 'windows-latest'
        run: |
          yarn electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}